POST http://localhost:8080/orders/create-order
Content-Type: application/json

{
  "customerName": "John Doe",
  "courierName": "DHL",
  "items": [
    { "productId": 1, "quantity": 2 },
    { "productId": 3, "quantity": 1 }
  ]
}